---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}-secret
data:
  GITHUB_TOKEN: {{ .Values.github.token | b64enc }}
  GITHUB_ORGANIZATION: {{ .Values.github.organization | b64enc }}
  GITHUB_REPOSITORY: {{ .Values.github.repository | b64enc }}
  GITHUB_REPOSITORY_PATH: {{ .Values.github.repository_path | b64enc }}
  GITHUB_BRANCH: {{ .Values.github.branch | b64enc }}
  COMMUNITY: {{ .Values.community | b64enc }}
  TAGS: {{ .Values.tags | b64enc }}
  NAMESPACE: {{ .Values.namespace | b64enc }}
  IMAGE: {{ .Values.image_url | b64enc }}
