# example secret that need to be created before installing nodejsweekly
# we separate the 
---
apiVersion: v1
kind: Secret
metadata:
  name: foo
data:
  GITHUB_TOKEN: foo
  GITHUB_ORGANIZATION: bar
  GITHUB_REPOSITORY: foo
  GITHUB_REPOSITORY_PATH: bar
  GITHUB_BRANCH: foo
