
cronSchedule: "0 8 * * 0"

image:
  repository: "zufardhiyaulhaq/nodejsweekly"
  tag: "v1.1.0"

secret: ""

weekly:
  community: "Node.js Indonesia Community"
  tags: "weekly,nodejs"
  namespace: "nodejs-community"
  image_url: "https://calebmadrigal.com/images/nodejs-logo.png"

